# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# C_CheckNoData.py
# Created on: 2019-02-21 12:08:30.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: C_CheckNoData <InGrid> <OutPolys_shp> 
# Description: 
# Finds NODATA values in a grid and makes a polygon feature class with value 1 if it is NODATA, and 0 if it contains data values. 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
InGrid = arcpy.GetParameterAsText(0)

OutPolys_shp = arcpy.GetParameterAsText(1)
if OutPolys_shp == '#' or not OutPolys_shp:
    OutPolys_shp = "C:\\Users\\tbarnhart\\RasterT_SingleO1.shp" # provide a default value if unspecified

# Local variables:
tmpGrid = "C:\\Users\\tbarnhart\\SingleOutput2"

# Process: Single Output Map Algebra
tempEnvironment0 = arcpy.env.extent
arcpy.env.extent = InGrid
tempEnvironment1 = arcpy.env.cellSize
arcpy.env.cellSize = InGrid
arcpy.gp.SingleOutputMapAlgebra_sa("con ( isnull ( InGrid ), 1 )", tmpGrid, "''")
arcpy.env.extent = tempEnvironment0
arcpy.env.cellSize = tempEnvironment1

# Process: Raster to Polygon
arcpy.RasterToPolygon_conversion(tmpGrid, OutPolys_shp, "NO_SIMPLIFY", "Value", "SINGLE_OUTER_PART", "")

