# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 2D_Fill_NoData_Cells.py
# Created on: 2019-02-21 16:28:59.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: 2D_Fill_NoData_Cells <InGrid> <OutGrid> 
# Description: 
# Replaces NODATA values in a grid with mean values within 3x3 window. May be run repeatedly to fill in areas wider than 2 cells. Note the output is floating point, even if the input is integer. Note this will expand the data area of the grid around the outer edges of data, in addition to filling in NODATA gaps in the interior of the grid.
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
InGrid = arcpy.GetParameterAsText(0)

OutGrid = arcpy.GetParameterAsText(1)
if OutGrid == '#' or not OutGrid:
    OutGrid = "C:\\Users\\tbarnhart\\SingleOutput2" # provide a default value if unspecified

# Local variables:

# Process: Single Output Map Algebra
tempEnvironment0 = arcpy.env.extent
arcpy.env.extent = InGrid
tempEnvironment1 = arcpy.env.cellSize
arcpy.env.cellSize = InGrid
arcpy.gp.SingleOutputMapAlgebra_sa("con ( isnull ( InGrid ) , focalmean ( InGrid  ) , InGrid  )
", OutGrid, "''")
arcpy.env.extent = tempEnvironment0
arcpy.env.cellSize = tempEnvironment1

