# ---------------------------------------------------------------------------
# LocalHUCProcessing.py
# Created on: Sat Apr 17 2010 10:31:54 AM
#   (generated by ArcGIS/ModelBuilder)
# Usage: LocalHUCProcessing <Fdr> <Fac> <Number_of_cells_to_define_stream__2_> <str900> <Snklnk> 
# Description: 
# Arc Hydro grid and geodatabase terrain preprocessing, starting with fdr and fac plus coastline/sink grids. 
# ---------------------------------------------------------------------------

# Import system modules
import sys, string, os, arcgisscripting

# Create the Geoprocessor object
gp = arcgisscripting.create()

# Load required toolboxes...
#gp.AddToolbox("C:/ArcGIS/ArcToolbox/Toolboxes/Arc Hydro Tools.tbx")

# Script arguments...
Fdr = sys.argv[1]
if Fdr == '#':
 Fdr = "Fdr" # provide a default value if unspecified

Fac = sys.argv[2]
if Fac == '#':
 Fac = "Fac" # provide a default value if unspecified

Number_of_cells_to_define_stream__2_ = sys.argv[3]
if Number_of_cells_to_define_stream__2_ == '#':
 Number_of_cells_to_define_stream__2_ = "20000" # provide a default value if unspecified

str900 = sys.argv[4]
if str900 == '#':
 str900 = "str900" # provide a default value if unspecified

Snklnk = sys.argv[5]
if Snklnk == '#':
 Snklnk = "snklnk" # provide a default value if unspecified

# Local variables...
StrLnk = "StrLnk"
DrainageLine = "DrainageLine"
Cat = "Cat"
Catchment = "Catchment"
AdjointCatchment = "AdjointCatchment"
DrainagePoint = "DrainagePoint"
Lnk = "Lnk"
str = "Str"
strlnk900 = "strlnk900"
streams900cells = "streams900cells"

# Process: Stream Definition...
gp.StreamDefinition_archydro(Fac, Number_of_cells_to_define_stream__2_, str)

# Process: Stream Segmentation...
gp.StreamSegmentation_archydro(str, Fdr, StrLnk, "", "")

# Process: Drainage Line Processing...
gp.DrainageLineProcessing_archydro(StrLnk, "Fdr", DrainageLine)

# Process: Combine Stream Link and Sink Link...
gp.CombineStreamLinkAndSinkLink_archydro(StrLnk, Snklnk, Lnk)

# Process: Catchment Grid Delineation...
gp.CatchmentGridDelineation_archydro("Fdr", Lnk, Cat)

# Process: Catchment Polygon Processing...
gp.CatchmentPolyProcessing_archydro(Cat, Catchment)

# Process: Adjoint Catchment Processing...
gp.AdjointCatchment_archydro(DrainageLine, Catchment, AdjointCatchment)

# Process: Drainage Point Processing...
gp.DrainagePointProcessing_archydro("Fac", Cat, Catchment, DrainagePoint)

# Process: Stream Segmentation (2)...
gp.StreamSegmentation_archydro(str900, Fdr, strlnk900, "", "")

# Process: Drainage Line Processing (2)...
gp.DrainageLineProcessing_archydro(strlnk900, Fdr, streams900cells)

