# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# PostHydroDEMProcessing_sinks.py
# Created on: 2019-08-06 10:30:44.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: PostHydroDEMProcessing_sinks <Fdr_grid> <Fac_grid> <Threshold1> <Snklnk_grid> <Threshold2> 
# Description: 
# Arc Hydro grid and geodatabase terrain preprocessing, starting with fdr and fac plus coastline/sink grids. 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Fdr_grid = arcpy.GetParameterAsText(0)
if Fdr_grid == '#' or not Fdr_grid:
    Fdr_grid = "Fdr" # provide a default value if unspecified

Fac_grid = arcpy.GetParameterAsText(1)
if Fac_grid == '#' or not Fac_grid:
    Fac_grid = "Fac" # provide a default value if unspecified

Threshold1 = arcpy.GetParameterAsText(2)
if Threshold1 == '#' or not Threshold1:
    Threshold1 = "150000" # provide a default value if unspecified

Snklnk_grid = arcpy.GetParameterAsText(3)
if Snklnk_grid == '#' or not Snklnk_grid:
    Snklnk_grid = "SinkLnk" # provide a default value if unspecified

Threshold2 = arcpy.GetParameterAsText(4)
if Threshold2 == '#' or not Threshold2:
    Threshold2 = "900" # provide a default value if unspecified

# Local variables:
str = "Str"
StrLnk = "StrLnk"
DrainageLine = "DrainageLine"
Lnk = "Lnk"
Cat = "Cat"
Catchment = "Catchment"
AdjointCatchment = "AdjointCatchment"
DrainagePoint = "DrainagePoint"
Str900 = "Str900"

# Process: Stream Definition
arcpy.StreamDefinition_archydro(Fac_grid, Threshold1, str, "15")

# Process: Stream Segmentation
arcpy.StreamSegmentation_archydro(str, Fdr_grid, StrLnk, "", "")

# Process: Drainage Line Processing
arcpy.DrainageLineProcessing_archydro(StrLnk, Fdr_grid, DrainageLine)

# Process: Combine Stream Link and Sink Link
arcpy.CombineStreamLinkAndSinkLink_archydro(StrLnk, Snklnk_grid, Lnk, "")

# Process: Catchment Grid Delineation
arcpy.CatchmentGridDelineation_archydro(Fdr_grid, Lnk, Cat)

# Process: Catchment Polygon Processing
arcpy.CatchmentPolyProcessing_archydro(Cat, Catchment)

# Process: Adjoint Catchment Processing
arcpy.AdjointCatchment_archydro(DrainageLine, Catchment, AdjointCatchment)

# Process: Drainage Point Processing
arcpy.DrainagePointProcessing_archydro(Fac_grid, Cat, Catchment, DrainagePoint)

# Process: Stream Definition (2)
arcpy.StreamDefinition_archydro(Fac_grid, Threshold2, Str900, "0.09")

