# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# post_hdrodem.py
# Created on: 2019-07-29 14:11:22.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: post_hdrodem <Fdr> <Fac> <Threshold1> <Threshold2> 
# Description: 
# Arc Hydro grid and geodatabase terrain preprocessing, starting with fdr and fac grids. 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Fdr = arcpy.GetParameterAsText(0)
if Fdr == '#' or not Fdr:
    Fdr = "fdr" # provide a default value if unspecified

Fac = arcpy.GetParameterAsText(1)
if Fac == '#' or not Fac:
    Fac = "fac" # provide a default value if unspecified

Threshold1 = arcpy.GetParameterAsText(2)
if Threshold1 == '#' or not Threshold1:
    Threshold1 = "150000" # provide a default value if unspecified

Threshold2 = arcpy.GetParameterAsText(3)
if Threshold2 == '#' or not Threshold2:
    Threshold2 = "900" # provide a default value if unspecified

# Local variables:
str = "Str"
StrLnk = "StrLnk"
DrainageLine = "DrainageLine"
Cat = "Cat"
Catchment = "Catchment"
AdjointCatchment = "AdjointCatchment"
DrainagePoint = "DrainagePoint"
Str900 = "Str900"

